service: cloud-guru-notes
frameworkVersion: '3'

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb: ${file(resources/config/dynamodb-config.yml)}
  esbuild: ${file(resources/config/esbuild-config.yml)}

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  timeout: 30
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-3'}
  environment:
    Notes_Table_Name: ${self:provider.stage}-notes
    ENV: ${self:provider.stage}

functions: ${file(resources/lambda-function.yml)}

resources:
  - ${file(resources/dynamodb.yml)}
